#FosUser
fos_user_security:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/fos_user/security.yml"

fos_user_profile:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/fos_user/profile.yml"
    prefix: /profil

fos_user_register:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/fos_user/registration.yml"
    prefix: /inscription

fos_user_resetting:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/fos_user/resetting.yml"
    prefix: /mot-de-passe-oublie

fos_user_change_password:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/fos_user/change_password.yml"
    prefix: /compte

#Sonata FosUser
sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting
