<?php

namespace AppBundle\Repository;

/**
 * UserInventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInventoryRepository extends \Doctrine\ORM\EntityRepository
{
}
