# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  sonata.admin.security.handler.role:
      class: Sonata\AdminBundle\Security\Handler\RoleSecurityHandler
      arguments: ['@security.authorization_checker', ["ROLE_ADMIN"]]

  #Event Listener
  request_listener:
      class: AppBundle\EventListener\RequestListener
      arguments: ["@service_container"]
      tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
